# Generated by Django 3.1.2 on 2020-10-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informacoes_peixe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peixe', models.CharField(help_text='Dê um nome ao peixe', max_length=20)),
                ('massa', models.FloatField(help_text='Insira a massa em KG')),
                ('tamanho', models.IntegerField(help_text='Insira o tamanho em CM')),
                ('imagem_peixe', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
