# Generated by Django 3.1.2 on 2020-10-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informacoes_pescaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora_pesca', models.TimeField()),
                ('acompanhantes', models.CharField(help_text='Insira os acompanhantes', max_length=100)),
                ('local_pesca', models.CharField(help_text='Insira a localização', max_length=150)),
            ],
        ),
    ]
