# Generated by Django 3.1.2 on 2020-10-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(help_text='Insira o nome do usuario', max_length=50)),
                ('cpf', models.FloatField(help_text='Insira o CPF', max_length=20)),
                ('telefone', models.IntegerField(help_text='Insira o telefone')),
                ('endereco', models.CharField(help_text='Insira o endereco', max_length=80)),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
